[package]
name = "wasm-greet"
version = "0.1.0"
authors = ["Mike Morris <mikemorris@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.45"
